name: Build / Test

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: install
        run: |
          yarn install
          node node_modules/puppeteer/install.js
          PUPPETEER_PRODUCT=firefox node node_modules/puppeteer/install.js

      - name: lint
        run: yarn lint

      - name: build
        run: |
          yarn build
          yarn link wc-ssr

      - name: unit test
        working-directory: ./__tests__
        run: yarn test:unit

      - name: unit test
        working-directory: ./__tests__
        run: yarn test:unit

      - name: run example for browser test
        working-directory: ./example
        run: |
          yarn install
          yarn start

      - name: browser test
        working-directory: ./__browserTests__
        run: yarn test:browser
